# Podfile
use_frameworks!

target 'BSTU App' do
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  pod 'RxGesture', '3.0.0'
  pod 'RxDataSources', '4.0.1'
  pod 'SQLite.swift', '0.12.2'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftSoup'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Hippolyte'
end